spring.application.name=FinanzApp
server.port=8081

# -------------------------
# H2 IN-MEMORY DATABASE
# -------------------------
spring.datasource.url=jdbc:h2:mem:finanzapp;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# -------------------------
# FLYWAY (ENABLED)
# -------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# -------------------------
# SWAGGER / OPENAPI
# -------------------------
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

# -------------------------
# ACTUATOR
# -------------------------
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# -------------------------
# PROFILE
# -------------------------
spring.profiles.active=dev


